Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /cube/ HTTP/1.1" 200 1
"GET /cube/ HTTP/1.1" 200 1
"GET /cube/ HTTP/1.1" 200 1
"GET /heads_tails HTTP/1.1" 301 0
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78319
Not Found: /index
"GET /index HTTP/1.1" 404 2425
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78319
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render('index.html')
           ^^^^^^^^^^^^^^^^^^^^
TypeError: render() missing 1 required positional argument: 'template_name'
"GET / HTTP/1.1" 500 63674
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render('index.html')
           ^^^^^^^^^^^^^^^^^^^^
TypeError: render() missing 1 required positional argument: 'template_name'
"GET / HTTP/1.1" 500 63811
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10
"GET / HTTP/1.1" 200 10
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78453
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78453
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 421
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1610
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1493
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1492
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1511
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1688
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1505
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 955
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1014
"GET / HTTP/1.1" 200 1015
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 1015
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
Not Found: /images/image.png
Not Found: /styles/style.css
"GET /images/image.png HTTP/1.1" 404 2458
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1825
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
Not Found: /my_app/index.html
"GET /my_app/index.html HTTP/1.1" 404 2461
"GET / HTTP/1.1" 200 1818
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
Not Found: /my_app/about.html
"GET /my_app/about.html HTTP/1.1" 404 2461
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
"GET / HTTP/1.1" 200 1818
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1813
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1796
Not Found: /images/image.png
Not Found: /styles/style.css
"GET /images/image.png HTTP/1.1" 404 2458
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1796
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1796
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1803
Not Found: /my_app/images/image.png
"GET /my_app/images/image.png HTTP/1.1" 404 2479
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1803
Not Found: /styles/style.css
Not Found: /my_app/images/image.png
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /my_app/images/image.png HTTP/1.1" 404 2479
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1887
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1887
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1842
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1783
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1783
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1784
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
Not Found: /hello
"GET /hello HTTP/1.1" 404 2533
Not Found: /magazin
"GET /magazin HTTP/1.1" 404 2539
"GET /magazin/hello HTTP/1.1" 301 0
"GET /magazin/hello/ HTTP/1.1" 200 26
"GET /magazin/hello2/ HTTP/1.1" 200 23
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
Not Found: /magazin
"GET /magazin HTTP/1.1" 404 2539
"GET /magazin/hello HTTP/1.1" 301 0
"GET /magazin/hello/ HTTP/1.1" 200 26
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
"GET /magazin HTTP/1.1" 301 0
"GET /magazin/ HTTP/1.1" 200 168
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
"GET /magazin/if HTTP/1.1" 301 0
"GET /magazin/if/ HTTP/1.1" 200 596
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 594
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 667
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 643
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 29, in get_context_data
    context['total_price'] = int(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'DeferredAttribute'
"GET /magazin/if/ HTTP/1.1" 500 78460
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 29, in get_context_data
    context['total_price'] = int(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'DeferredAttribute'
"GET /magazin/if/ HTTP/1.1" 500 78460
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    context['total_price'] = decimal(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decimal() argument 1 must be a unicode character, not DeferredAttribute
"GET /magazin/if/ HTTP/1.1" 500 78344
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Internal Server Error: /orders/2
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/2 HTTP/1.1" 500 132742
Internal Server Error: /orders/1
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/1 HTTP/1.1" 500 132732
Watching for file changes with StatReloader
Internal Server Error: /orders/1
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/1 HTTP/1.1" 500 132869
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Internal Server Error: /orders/10
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/10 HTTP/1.1" 500 132731
Not Found: /order/10
"GET /order/10 HTTP/1.1" 404 2683
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
"GET /magazin/ HTTP/1.1" 200 168
Not Found: /magazin/1
"GET /magazin/1 HTTP/1.1" 404 3274
"GET /magazin/if HTTP/1.1" 301 0
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(pk=self.kwargs['id_user'])
                               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78185
Not Found: /magazin/if/1
"GET /magazin/if/1 HTTP/1.1" 404 3283
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(pk=self.kwargs['id_user'])
                               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78185
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
Not Found: /user/add
"GET /user/add HTTP/1.1" 404 2683
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /les4/user/add HTTP/1.1" 301 0
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/user_form.html
"GET /les4/user/add/ HTTP/1.1" 500 80079
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/user_form.html
"GET /les4/user/add/ HTTP/1.1" 500 80079
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/user_form.html
"GET /les4/user/add/ HTTP/1.1" 500 80061
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/user_form.html
"GET /les4/user/add/ HTTP/1.1" 500 80061
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 130932
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 130932
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 130932
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 130932
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 131129
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 131502
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py", line 21, in user_form
    return render(request, 'myapp4/user_form.html', {'form':form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /les4/user/add/ HTTP/1.1" 500 131502
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /les4/user/add/ HTTP/1.1" 200 1155
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /les4/user/add/ HTTP/1.1" 200 1155
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67514
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67514
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67514
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67497
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67497
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67517
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67516
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67522
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67517
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"GET /les4/user/add/ HTTP/1.1" 500 66136
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"GET /les4/user/add/ HTTP/1.1" 500 66273
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"GET /les4/user/add/ HTTP/1.1" 500 66273
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp4\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67522
"GET /les4/user/add/ HTTP/1.1" 200 1167
Internal Server Error: /les4/user/add/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
"POST /les4/user/add/ HTTP/1.1" 500 67576
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2797
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5852
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Watching for file changes with StatReloader
"GET /admin/auth/user/ HTTP/1.1" 200 11308
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
"GET /static/admin/js/core.js HTTP/1.1" 200 5682
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/user/add/ HTTP/1.1" 200 10988
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/css/forms.css HTTP/1.1" 200 9047
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"POST /admin/auth/user/add/ HTTP/1.1" 200 11443
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/auth/user/add/ HTTP/1.1" 200 11291
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 22723
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15292
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 11918
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/group/ HTTP/1.1" 200 7641
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/group/add/ HTTP/1.1" 200 12107
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 9108
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/user/ HTTP/1.1" 200 11999
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 22592
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 12221
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/logout/ HTTP/1.1" 200 3709
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 4797
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp5\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 4797
"POST /admin/logout/ HTTP/1.1" 200 3709
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 8625
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 10248
"POST /admin/logout/ HTTP/1.1" 200 3709
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 6287
"GET /admin/magazin_app/order/ HTTP/1.1" 200 21307
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 17895
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 19852
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 21307
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/logout/ HTTP/1.1" 200 3709
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 10248
"GET /admin/myapp5/product/add/ HTTP/1.1" 200 12344
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/myapp5/product/add/ HTTP/1.1" 302 0
"GET /admin/myapp5/product/add/ HTTP/1.1" 200 12628
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/myapp5/product/add/ HTTP/1.1" 302 0
"GET /admin/myapp5/product/ HTTP/1.1" 200 11272
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/ HTTP/1.1" 200 9595
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/add/ HTTP/1.1" 200 13601
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/myapp5/product/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6368
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/myapp5/order/add/ HTTP/1.1" 200 13781
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/ HTTP/1.1" 200 6258
"GET /admin/ HTTP/1.1" 200 10820
"GET /admin/magazin_app/product/ HTTP/1.1" 200 19950
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 23362
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/add/ HTTP/1.1" 200 19285
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/order/add/ HTTP/1.1" 302 0
"GET /admin/magazin_app/order/ HTTP/1.1" 200 23964
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/ HTTP/1.1" 200 9595
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/add/ HTTP/1.1" 200 13601
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/user/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6337
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/user/ HTTP/1.1" 200 9588
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/user/add/ HTTP/1.1" 200 12304
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/ HTTP/1.1" 200 9595
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/add/ HTTP/1.1" 200 13601
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 21907
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/add/ HTTP/1.1" 200 12324
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/user/add/ HTTP/1.1" 302 0
"GET /admin/magazin_app/user/ HTTP/1.1" 200 22430
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/order/ HTTP/1.1" 200 9595
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/product/ HTTP/1.1" 200 11067
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/user/ HTTP/1.1" 200 9588
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 23664
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/myapp5/ HTTP/1.1" 200 6173
"GET /admin/myapp5/ HTTP/1.1" 200 6173
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp5\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\myapp5\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 9886
"GET /admin/ HTTP/1.1" 200 9886
"GET /admin/magazin_app/order/ HTTP/1.1" 200 22524
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/auth/user/ HTTP/1.1" 200 13189
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/auth/user/ HTTP/1.1" 200 13189
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 22524
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 18810
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 21030
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 22524
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 18810
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/42/change/ HTTP/1.1" 200 11492
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/product/42/change/ HTTP/1.1" 302 0
"GET /admin/magazin_app/product/ HTTP/1.1" 200 19034
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/42/change/ HTTP/1.1" 200 11492
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/product/42/change/ HTTP/1.1" 302 0
"GET /admin/magazin_app/product/ HTTP/1.1" 200 19034
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/41/change/ HTTP/1.1" 200 11492
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/product/41/change/ HTTP/1.1" 302 0
"GET /admin/magazin_app/product/ HTTP/1.1" 200 19034
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/ HTTP/1.1" 200 27262
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/ HTTP/1.1" 200 27262
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 26277
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 28069
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 27262
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?o=3 HTTP/1.1" 200 28688
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?o= HTTP/1.1" 200 28337
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/?o= HTTP/1.1" 200 28337
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?o=4 HTTP/1.1" 200 28688
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?o= HTTP/1.1" 200 28337
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/?o= HTTP/1.1" 200 28337
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 28377
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/ HTTP/1.1" 200 29745
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 27238
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/?ordered_at__gte=2023-09-05+00%3A00%3A00%2B00%3A00&ordered_at__lt=2023-09-13+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 33069
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/?ordered_at__gte=2023-01-01+00%3A00%3A00%2B00%3A00&ordered_at__lt=2024-01-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 33069
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/?ordered_at__gte=2023-09-01+00%3A00%3A00%2B00%3A00&ordered_at__lt=2023-10-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 33069
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/?ordered_at__gte=2023-09-12+00%3A00%3A00%2B00%3A00&ordered_at__lt=2023-09-13+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 11919
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/?ordered_at__gte=2023-01-01+00%3A00%3A00%2B00%3A00&ordered_at__lt=2024-01-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 33069
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 29866
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 29745
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?address=Rossia HTTP/1.1" 200 13473
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?address=Some+address HTTP/1.1" 200 30392
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/? HTTP/1.1" 200 29745
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 27238
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 29866
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?price=1000.00 HTTP/1.1" 200 13982
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/? HTTP/1.1" 200 29866
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/? HTTP/1.1" 200 30181
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 30060
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?q=john HTTP/1.1" 200 13673
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/?q=john HTTP/1.1" 200 13241
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/?q=john HTTP/1.1" 200 13241
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30320
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/ HTTP/1.1" 200 30209
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?q=mane HTTP/1.1" 200 11156
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?q=mane1 HTTP/1.1" 200 11167
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/?q=name HTTP/1.1" 200 30048
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/? HTTP/1.1" 200 30209
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/? HTTP/1.1" 200 30209
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30320
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
Internal Server Error: /admin/magazin_app/product/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'quantity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1959, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1593, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py", line 7, in reset_quantity
    queryset.update(quantity=0)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1188, in update
    query.add_update_values(kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Product has no field named 'quantity'
"POST /admin/magazin_app/product/ HTTP/1.1" 500 124407
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/product/ HTTP/1.1" 302 0
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/?o=4.3 HTTP/1.1" 200 31839
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"POST /admin/magazin_app/product/?o=4.3 HTTP/1.1" 302 0
"GET /admin/magazin_app/product/?o=4.3 HTTP/1.1" 200 31839
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/7/change/?_changelist_filters=o%3D4.3 HTTP/1.1" 200 11579
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/7/change/?_changelist_filters=o%3D4.3 HTTP/1.1" 200 10875
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/product/7/change/?_changelist_filters=o%3D4.3 HTTP/1.1" 200 11579
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 30209
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/3/change/ HTTP/1.1" 200 11515
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/27/change/ HTTP/1.1" 200 11493
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/product/ HTTP/1.1" 200 30413
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/order/ HTTP/1.1" 200 27238
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/ HTTP/1.1" 200 30209
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /admin/magazin_app/user/15/change/ HTTP/1.1" 200 11515
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/magazin_app/user/15/change/ HTTP/1.1" 200 11860
"GET /admin/jsi18n/ HTTP/1.1" 200 16066
"GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12023
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13404
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 12698
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=HistoryPanel HTTP/1.1" 200 4155
"GET /static/debug_toolbar/js/history.js HTTP/1.1" 200 3330
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=VersionsPanel HTTP/1.1" 200 760
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=SettingsPanel HTTP/1.1" 200 27025
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=HeadersPanel HTTP/1.1" 200 5345
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=RequestPanel HTTP/1.1" 200 2310
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=SQLPanel HTTP/1.1" 200 30138
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=StaticFilesPanel HTTP/1.1" 200 36859
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=TemplatesPanel HTTP/1.1" 200 4338
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=CachePanel HTTP/1.1" 200 1737
"GET /__debug__/render_panel/?store_id=4e92a0434bbd4cec9e5511247de8b76c&panel_id=SignalsPanel HTTP/1.1" 200 2231
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 138249
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 138249
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\debug_toolbar\toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 138249
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2812
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 179
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 77, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\conf\__init__.py", line 111, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 179
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 179
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
